apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: dev
spec:
  encryptedData:
    password: AgBuYqPP7+zicgNq3atwfQ0En7o8XCHP3hqfr/+Jm/b0EKh4e366bfToGIgHN08QZdzXMqEzo0AuEAEDxOsy1976Tk0Brme+lmb9FKs1XjJJkkI1Blps4r61FoDhLlTcveMDOTH+d/K88aHx98PsvFvp4LxMxPUqM8dzDG+CXIyzKxzRlqlKa56Tseg/WTqoF2QUAzNvp2PjwzZUSqmCb0030ESk0XA2U2LpbnTGRUcw2qJU5JRto7Vaf2o/eC53z1/H4kAWq1o0pKBmN1Y09nLN7b7FnnjrdKtBHyK9q8o6ApBdEPjYWHcgMxyQWs+AYd7u4tCG+81ikXVKba/Elu7WFaDma8qf1wLwODMzumRGrBmkNM4F80BJyEK0maP4fjbMHJRJ17JOsGDvqq1+4UBSYpcigDB1YVMUUOX1Rgbw36kLuviWboUReffLME0mycBBi5UOy4G1opSyLBFXDpKT8zx4qwc21Fp99mOMhiep2lyC22YblZA2SQkhG5NdBnFfHBw9DxYVVI/RhV3Nfr/F/MAT04bGjQCkG9hohnZpeX8MJRtvIzCOgB4PJ576p98mKpHm6exJBejydAYRmEJQvggt4tKOdtXr+OD3ZbxtLmyM4VTaPDAvSKzDawQGUQjSmtOCMQxwEtVusXBYwSGA2iaecymarh4AvEOd5d6CINMjjF4v6fFhCjih6Snd5R0hPpIfBA==
    user: AgBdg8Qd8YhAxzLAvMcWXCrWv/hY+FWhQgcITpL/1Keies7MnNmg3L3Mm/ZWCGBOtsZ2/JvnyP01ANyaa0sHoUe5JUr8o1C5NB1KA2oJ1hty0az+qWjp3zwi4aSwMhkMO5fzKKTkDJWR3oAtQ0MU8TXkV4N6v3vsPTs4wJ706BFICS5+Eh66jebdO5M8RVcdy2T1m5EiQCrDouPrPVRl9Kbd9k7bY4g1xRaA8b9Q/KVY/BLKPl9yKd+Spxz3ZxB9NSh5AJ0l6g3nNgGDFZfdUWF46nUUAIfIDfFx3OKE+WssW7QsElOnvtfDsnjmwhGSMj+L7ENDaKPuhjclRxodnaiF4+QOp+l9y86/kkNrepHnedroqWf7de0FKF8y9p6IuV8feSNXYIF+dLsE0C+DTqDYrVBqKpmYcewT2nBS79QgynWD8NQ4zTqDuf6zpNx/Ey5pa+jvmkXRsJCwrsf6z/TZv4VxF4kQ3mivuc7p6c/j+lNDeu5V3p+FTmQwVZsbcG1MHa5jO666UB+XI+28cYzxudIuIH5esxV6vPsZx1cNMUWEIWesS6kN5JtY1f3iyWBfFcYbaWQu8TMDtzYVTg0pWu1aN5i2zt5Lsz5mAvBI/8zmv0LO42O5kUq6NC0+ifqB5kFucnr4yUSHl32WOeYlipUfzE+v2rJVy+A1ZhqucZ5MWTNGbkBrp67ogf8V8h0ALUGAkA==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: dev

